steps:
  - name: "gcr.io/cloud-builders/docker"
    args: [ "build", "-t", "asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pf-dtm:$COMMIT_SHA", "-f", "Dockerfile", "." ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pf-dtm:$COMMIT_SHA"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
    - "run"
    - "deploy"
    - "dtm"
    - "--args"
    - "-c /secrets/config.yaml"
    - "--image"
    - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pf-dtm:$COMMIT_SHA"
    - "--region"
    - "asia-northeast1"
    - "--port"
    - "443"
    - "--vpc-connector"
    - "main-connector"
    - "--update-secrets=/secrets/config.yaml=dtm-config:latest"
    - "--use-http2"
    - "--allow-unauthenticated"
images:
  - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pf-dtm:$COMMIT_SHA"